# Generated by Django 5.0.14 on 2025-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="renenwal_date",
            new_name="renewal_date",
        ),
    ]
