# Generated by Django 5.0.14 on 2025-04-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_rename_renenwal_date_subscription_renewal_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[("Email", "Email"), ("In-App", "In-App")],
                        max_length=50,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
    ]
