# Generated by Django 5.0.14 on 2025-04-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="remind_method",
            field=models.CharField(
                choices=[("Email", "Email"), ("In-App", "In-App")],
                default="In-App",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.subscription",
            ),
        ),
    ]
